id: I57DFFB75
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:41:16+00:00'
last_modified: '2022-06-07T12:25:09.932933+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC261
  title: གངས་ཅན་བརྡ་དག་བློ་གསལ་དགྱེས་པའི་རོལ་མཚོ་དང་བོད་ཀྱི་བརྡ་དག་ལ་བརྟེན་ནས་ཤེས་བྱ་ཀུན་ལ་འཇུག་པའི་སྒོ་རྣམ་པར་དབྱེ་བ་ནོར་བུའི་མེ་ལོང་།༼སྟོད་ཆ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A639:
      image_group_id: I2PD18759
      title: ''
      total_pages: 142
      order: 1
      base_file: A639.txt
    4C07:
      image_group_id: I2PD18760
      title: ''
      total_pages: 390
      order: 2
      base_file: 4C07.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
