id: opecha:P000598
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC261
  title: གངས་ཅན་བརྡ་དག་བློ་གསལ་དགྱེས་པའི་རོལ་མཚོ་དང་བོད་ཀྱི་བརྡ་དག་ལ་བརྟེན་ནས་ཤེས་བྱ་ཀུན་ལ་འཇུག་པའི་སྒོ་རྣམ་པར་དབྱེ་བ་ནོར་བུའི་མེ་ལོང་།༼སྟོད་ཆ།༽
  volume: ''
  author: ''
