id: P000598
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC261
  title: གངས་ཅན་བརྡ་དག་བློ་གསལ་དགྱེས་པའི་རོལ་མཚོ་དང་བོད་ཀྱི་བརྡ་དག་ལ་བརྟེན་ནས་ཤེས་བྱ་ཀུན་ལ་འཇུག་པའི་སྒོ་རྣམ་པར་དབྱེ་བ་ནོར་བུའི་མེ་ལོང་།༼སྟོད་ཆ།༽
  author: ''
  volumes:
    37bf4cc40f994874ae93ae37fa8c5738:
      image_group_id: I2PD18759
      title: ''
      volume_number: 1
      total_pages: 142
    81d76dd7d0984a5894e9b0966d5235bc:
      image_group_id: I2PD18760
      title: ''
      volume_number: 2
      total_pages: 390
